# Any file that is not a doc *.md file
src:
  - "!docs/**"
  - "!**/*.md"
  - "!*.md"
  - "!.github/CONTRIBUTING.md"
  - "!.github/PULL_REQUEST_TEMPLATE.md"
  - "!**/README.md"
  - "!**/CHANGELOG.md"
