[book]
authors = ["Linode"]
language = "en"
multilingual = false
src = "src"
title = "Linode Cloud Controller Manager"
description = "Documentation for the Kubernetes Cloud Controller Manager for Linode"

[output.html]
git-repository-url = "https://github.com/linode/linode-cloud-controller-manager"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
