name: Publish Docker Canary
on:
  push:
    branches:    
      - master 
jobs:
  build:
    env:
      IMG: linode/linode-cloud-controller-manager:canary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker hub login
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Docker build
      run: make docker-build
    - name: Docker push
      run: make docker-push
        
