name: Publish Docker Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: make build-linux
    - name: Publish latest to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: linode/linode-cloud-controller-manager
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"
