name: 'Nightly Merge'

on:
  push:
    branches:
        - main

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full clone necessary for proper merge

    - name: Merge main into gh-pages
      uses: robotology/gh-action-nightly-merge@v1.5.2
      with:
        stable_branch: 'main'
        development_branch: 'gh-pages'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}