name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: lint
        run: make lint
      - name: build
        run: make docker-build
      - name: unit test
        run: make test
      - name: helm lint
        run: make helm-lint
      - name: helm template
        run: make helm-template